version: '3.1'
services:
  web:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost" ]
      interval: 5s
      timeout: 3s
      retries: 3
    depends_on:
      - app
  app:
    build: .
    expose:
      - 8080
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
