logging:
  level:
    root: warn
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 20MB
  profiles:
    active: local # 디폴트 환경
    include:
      - oauth
      - credentials
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version : 0

blog:
  title: Blog
  banner:
    title: Warning
    content: The blog will be down tomorrow.

cloud:
  aws:
    s3:
      bucket: secret
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true

aws:
  s3:
    bucket: secret
